### ISSUE TITLE
the images are different sizes so carousel resizes for every new image

### ISSUE THREAD

**Issue by saiyerniakhil** [Saif-Shines/SathyabamaTBIwebsite#1]

**Comment by Saif-Shines** [comment]
Hi @saiyerniakhil,

Yes, you can resize them and give me a Pull request, I'll add them in.

**Comment by Saif-Shines** [comment]
I'm checking your pull request @saiyerniakhil ! I'll soon add it to the master branch. 
So, I'll be closing this issue.
