### ISSUE TITLE
Problem with carousel

### ISSUE THREAD

**Issue by saiyerniakhil** [Saif-Shines/SathyabamaTBIwebsite#3]
The carousel displays 6 images but the carousel contains only three dots for active image indication

**Comment by saiyerniakhil** [comment]
Yes me too finding some issues and I'll be reporting them whenever I find them

**Comment by Saif-Shines** [comment]
Is the problem still up there?

**Comment by Saif-Shines** [comment]
Is it okay now?

**Comment by ShanmukhaSrinivas** [comment]
Problem Solved
